#!/usr/bin/env bash
set -eo pipefail

BUILDPACK_INSTALL_PATH="/tmp/buildpacks"

download_buildpack() {
    buildpack_url="https://github.com/heroku/$1.git"
    buildpack_commit=`curl -s https://api.github.com/repos/heroku/$1/tags | python -c "import sys, json; print json.load(sys.stdin)[0]['name']"`
    buildpack_name="$2"

    echo "Fetching $buildpack_name from $buildpack_commit... "

    set +e
    git clone --branch "$buildpack_commit" --depth 1 "$buildpack_url" $BUILDPACK_INSTALL_PATH/"$buildpack_name" &>/dev/null
    SHALLOW_CLONED=$?
    set -e
    if [ $SHALLOW_CLONED -ne 0 ]; then
        # if the shallow clone failed partway through, clean up and try a full clone
        rm -rf "${BUILDPACK_INSTALL_PATH:?}"/"$buildpack_name"
        git clone --quiet "$buildpack_url" $BUILDPACK_INSTALL_PATH/"$buildpack_name"
        pushd $BUILDPACK_INSTALL_PATH/"$buildpack_name" &>/dev/null
            git checkout --quiet "$buildpack_commit"
        popd &>/dev/null
    fi

    echo "Done."
}

mkdir -p $BUILDPACK_INSTALL_PATH

download_buildpack heroku-buildpack-multi          01-multi
download_buildpack heroku-buildpack-clojure        02-clojure
download_buildpack heroku-buildpack-go             03-go
download_buildpack heroku-buildpack-gradle         04-gradle
download_buildpack heroku-buildpack-grails         05-grails
download_buildpack heroku-buildpack-java           06-java
download_buildpack heroku-buildpack-nodejs         07-nodejs
download_buildpack heroku-buildpack-php            08-php
download_buildpack heroku-buildpack-play           09-play
download_buildpack heroku-buildpack-python         10-python
download_buildpack heroku-buildpack-ruby           11-ruby
download_buildpack heroku-buildpack-scala          12-scala
